import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import uuid
from decimal import Decimal

if sys.stdout.encoding != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

from sqlalchemy import text

from app.core.security import hash_password
from app.db.base import Base
from app.db.session import SessionLocal, engine
from app.models.category import Category
from app.models.product import Product
from app.models.product_image import ProductImage
from app.models.slug_redirect import SlugRedirect
from app.models.user import User, UserRole


def seed_database():
    print("Migrating schema & Creating all tables in PostgreSQL...")
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        # Schema Migration: Add SEO columns if not exist
        migration_sqls = [
            "ALTER TABLE categories ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255);",
            "ALTER TABLE categories ADD COLUMN IF NOT EXISTS meta_description VARCHAR(500);",
            "ALTER TABLE categories ADD COLUMN IF NOT EXISTS meta_keywords VARCHAR(255);",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255);",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS meta_description VARCHAR(500);",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS meta_keywords VARCHAR(255);",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS canonical_url VARCHAR(500);",
        ]
        for sql in migration_sqls:
            try:
                db.execute(text(sql))
            except Exception:
                pass
        db.commit()

        # 1. Seed Users
        admin_user = db.query(User).filter(User.email == "admin@vanbass.vn").first()
        if not admin_user:
            admin_user = User(
                id=uuid.uuid4(),
                email="admin@vanbass.vn",
                password_hash=hash_password("admin123456"),
                role=UserRole.ADMIN,
                is_active=True,
            )
            db.add(admin_user)
            print("Created default admin user: admin@vanbass.vn")

        customer_user = db.query(User).filter(User.email == "customer@vanbass.vn").first()
        if not customer_user:
            customer_user = User(
                id=uuid.uuid4(),
                email="customer@vanbass.vn",
                password_hash=hash_password("vanbass123"),
                role=UserRole.CUSTOMER,
                is_active=True,
            )
            db.add(customer_user)
            print("Created default customer user: customer@vanbass.vn")

        db.commit()

        # 2. Seed 5 Categories with SEO Metadata (VanBass Music Center)
        categories_data = [
            {
                "slug": "dj",
                "name": "Thiết bị DJ",
                "description": "Bàn DJ All-In-One, DJ Controller, Đầu phát CDJ, Mâm đĩa than Turntables chính hãng AlphaTheta & Pioneer DJ.",
                "meta_title": "Thiết Bị DJ Chính Hãng Đà Nẵng | Pioneer DJ & AlphaTheta - VanBass",
                "meta_description": "Phân phối và cho thuê bàn DJ, DJ Controller, CDJ Pioneer, AlphaTheta chính hãng tại VanBass Music Center Đà Nẵng. Bảo hành 12 tháng.",
                "meta_keywords": "thiết bị dj đà nẵng, mua bàn dj, thuê bàn dj đà nẵng, pioneer dj, alphatheta",
            },
            {
                "slug": "mixer",
                "name": "Mixer & Bàn trộn",
                "description": "Mixer DJ 2 kênh, 4 kênh, 6 kênh chuẩn club quốc tế và bộ xử lý tín hiệu DSP Marani Pro Audio.",
                "meta_title": "Bàn Trộn Âm Thanh & Mixer DJ Chuyên Nghiệp Đà Nẵng | VanBass",
                "meta_description": "Các dòng mixer DJ chuẩn club quốc tế Pioneer DJM-A9, DJM-V10, DJM-V5 và bộ xử lý DSP Marani chính hãng tại Đà Nẵng.",
                "meta_keywords": "mixer dj đà nẵng, bàn trộn âm thanh, djm a9, djm v10, djm v5, mixer pioneer, dsp marani",
            },
            {
                "slug": "audio",
                "name": "Loa & Pro Audio",
                "description": "Loa biểu diễn di động SonicLink, loa cột PA JBL, loa kiểm âm Monitor và củ loa rời B&C Speakers Italy.",
                "meta_title": "Loa Biểu Diễn & Củ Loa B&C Speakers Italy Đà Nẵng | VanBass",
                "meta_description": "Bán và cho thuê loa biểu diễn AlphaTheta WAVE-EIGHT, JBL EON ONE, loa kiểm âm Pioneer VM và củ loa rời B&C Speakers chính hãng.",
                "meta_keywords": "loa dj đà nẵng, thuê loa sự kiện, alphatheta wave eight, b&c speakers đà nẵng, loa kiểm âm",
            },
            {
                "slug": "stage-effects",
                "name": "Hiệu ứng & Máy khói",
                "description": "Máy tạo khói sân khấu, máy khói lạnh, máy khói đứng LED, quạt điều hướng và dung dịch khói chuẩn Antari Châu Âu.",
                "meta_title": "Máy Tạo Khói & Hiệu Ứng Sân Khấu Antari Chính Hãng | VanBass Đà Nẵng",
                "meta_description": "Phân phối và cho thuê máy khói Antari Z-1500II, máy khói lạnh Ice-101, khói đứng LED RGBA M-7 và dung dịch FLG-5 chính hãng.",
                "meta_keywords": "máy khói antari, thuê máy khói đà nẵng, máy khói lạnh, antari z1500ii, dung dịch tạo khói",
            },
            {
                "slug": "accessories",
                "name": "Tai nghe & Phụ kiện",
                "description": "Tai nghe DJ chuyên nghiệp, hệ thống micro không dây Sennheiser UHF và cáp tín hiệu Klotz cao cấp Made in Germany.",
                "meta_title": "Tai Nghe DJ & Phụ Kiện Âm Thanh Sennheiser Klotz | VanBass Đà Nẵng",
                "meta_description": "Tai nghe DJ AlphaTheta HDJ-F10 SonicLink, Pioneer HDJ-X10, micro không dây Sennheiser EW-D và cáp tín hiệu Klotz tại Đà Nẵng.",
                "meta_keywords": "tai nghe dj, micro sennheiser đà nẵng, dây cáp klotz, phụ kiện dj đà nẵng",
            },
        ]

        cat_map = {}
        for cat_info in categories_data:
            cat = db.query(Category).filter(Category.slug == cat_info["slug"]).first()
            if not cat:
                cat = Category(
                    id=uuid.uuid4(),
                    slug=cat_info["slug"],
                    name=cat_info["name"],
                    description=cat_info["description"],
                    meta_title=cat_info["meta_title"],
                    meta_description=cat_info["meta_description"],
                    meta_keywords=cat_info["meta_keywords"],
                    is_active=True,
                )
                db.add(cat)
                db.flush()
                print(f"Created category: {cat.name}")
            else:
                cat.name = cat_info["name"]
                cat.description = cat_info["description"]
                cat.meta_title = cat_info["meta_title"]
                cat.meta_description = cat_info["meta_description"]
                cat.meta_keywords = cat_info["meta_keywords"]
            cat_map[cat_info["slug"]] = cat.id

        db.commit()

        # 3. Seed Exactly 10 Authentic Products per Category (50 Total)
        products_data = [
            # === CATEGORY 1: THIẾT BỊ DJ (10 sản phẩm) ===
            {
                "name": "Thiết bị DJ All-in-one AlphaTheta XDJ-AN",
                "slug": "alphatheta-xdj-an",
                "sku": "XDJ-AN-AT",
                "category_slug": "dj",
                "brand": "AlphaTheta",
                "sale_enabled": True,
                "sale_price": Decimal("37227600"),
                "rental_enabled": True,
                "rental_price": Decimal("1200000"),
                "stock_quantity": 8,
                "description": "Hệ thống DJ all-in-one thế hệ mới từ AlphaTheta tích hợp màn hình cảm ứng 7 inch, hỗ trợ phát nhạc không dây và biểu diễn độc lập không cần máy tính.",
                "specifications": {
                    "Màn hình": "7 inch cảm ứng đa điểm HD",
                    "Số kênh": "2 kênh độc lập",
                    "Cổng kết nối": "USB-A x2, USB-B x1, Master XLR/RCA, Mic XLR",
                    "Phần mềm tương thích": "rekordbox, Serato DJ Pro",
                    "Bảo hành": "Chính hãng 12 tháng tại VanBass Music Center",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/gmusic-alphatheta-xdj-an-1_22224c38ede24f9cb9b58dc6cba20e62_large.png",
                "meta_title": "Bàn DJ AlphaTheta XDJ-AN All-in-One Chính Hãng | VanBass",
                "meta_description": "Mua & thuê bàn DJ AlphaTheta XDJ-AN chính hãng tại VanBass Đà Nẵng.",
            },
            {
                "name": "Đầu phát đa phương tiện DJ AlphaTheta CDJ-1500X",
                "slug": "alphatheta-cdj-1500x",
                "sku": "CDJ-1500X-AT",
                "category_slug": "dj",
                "brand": "AlphaTheta",
                "sale_enabled": True,
                "sale_price": Decimal("49680000"),
                "rental_enabled": True,
                "rental_price": Decimal("1500000"),
                "stock_quantity": 5,
                "description": "Đầu phát DJ chuyên nghiệp hỗ trợ Pro DJ Link, mâm xoay Full-size 206mm siêu mượt mà và bộ giải mã âm thanh 96kHz/32-bit trung thực.",
                "specifications": {
                    "Mâm xoay": "Full size 206mm kèm On Jog Display",
                    "Bộ giải mã": "DAC 96kHz / 32-bit",
                    "Kết nối mạng": "Gigabit Pro DJ Link LAN",
                    "Hỗ trợ file": "FLAC, ALAC, WAV, AIFF, MP3, AAC",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/cdj-1500x_large.png",
                "meta_title": "Đầu Phát DJ AlphaTheta CDJ-1500X Chuyên Nghiệp | VanBass",
                "meta_description": "Đầu phát DJ AlphaTheta CDJ-1500X chính hãng tại VanBass Music Center.",
            },
            {
                "name": "Đầu phát đa phương tiện DJ AlphaTheta CDJ-3000X",
                "slug": "alphatheta-cdj-3000x",
                "sku": "CDJ-3000X-AT",
                "category_slug": "dj",
                "brand": "AlphaTheta",
                "sale_enabled": True,
                "sale_price": Decimal("89910000"),
                "rental_enabled": True,
                "rental_price": Decimal("2500000"),
                "stock_quantity": 4,
                "description": "Flagship đầu phát DJ cao cấp nhất thế giới, trang bị vi xử lý MPU đa lõi siêu tốc và màn hình cảm ứng độ phân giải cao 9 inch.",
                "specifications": {
                    "Màn hình": "9 inch HD Touchscreen độ sáng cao",
                    "Bộ vi xử lý": "Dual-Core MPU hiệu năng cao",
                    "DAC": "Asahi Kasei 32-bit D/A Converter",
                    "Phím Hot Cue": "8 phím xếp ngang trực quan",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/cdj-3000_large.png",
                "meta_title": "Flagship Đầu Phát DJ AlphaTheta CDJ-3000X | VanBass",
                "meta_description": "Flagship CDJ-3000X chính hãng tại VanBass Music Center.",
            },
            {
                "name": "Hệ thống DJ All-in-one Pioneer DJ OPUS-QUAD",
                "slug": "pioneer-dj-opus-quad",
                "sku": "OPUS-QUAD-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("89000000"),
                "rental_enabled": True,
                "rental_price": Decimal("2500000"),
                "stock_quantity": 3,
                "description": "Tuyệt tác thiết kế hệ thống DJ all-in-one 4 deck độc lập sang trọng, chất âm thượng hạng 32-bit ESS Technology và khả năng phát nhạc Zone Output 2 không gian.",
                "specifications": {
                    "Số kênh": "4 Deck độc lập",
                    "Màn hình": "10.1 inch cảm ứng điện dung + màn hình hiển thị riêng từng deck",
                    "Zone Output": "Phát 2 nguồn nhạc riêng biệt cho 2 khu vực",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/opus-quad_large.png",
                "meta_title": "Bàn DJ Pioneer DJ OPUS-QUAD 4 Deck Độc Lập | VanBass",
                "meta_description": "Hệ thống Pioneer DJ OPUS-QUAD chính hãng tại VanBass Đà Nẵng.",
            },
            {
                "name": "Hệ thống DJ All-in-one Pioneer DJ XDJ-XZ",
                "slug": "pioneer-dj-xdj-xz",
                "sku": "XDJ-XZ-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("74000000"),
                "rental_enabled": True,
                "rental_price": Decimal("2200000"),
                "stock_quantity": 4,
                "description": "Hệ thống DJ all-in-one 4 kênh chuẩn Club NXS2 mạnh mẽ, mâm xoay Full-size kèm On Jog Color Display và 14 Beat FX chuyên nghiệp.",
                "specifications": {
                    "Số kênh": "4 kênh (2 kênh Standalone + 2 kênh ngoài)",
                    "Mâm xoay": "Full size 206mm On Jog Display",
                    "Pro DJ Link": "Đồng bộ nhạc với CDJ ngoài",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/xdj-xz_large.png",
                "meta_title": "Bàn DJ Pioneer DJ XDJ-XZ 4 Kênh All-in-One | VanBass",
                "meta_description": "Mua & thuê bàn DJ XDJ-XZ chuẩn club quốc tế tại Đà Nẵng.",
            },
            {
                "name": "Hệ thống DJ All-in-one Pioneer DJ XDJ-RX3",
                "slug": "pioneer-dj-xdj-rx3",
                "sku": "XDJ-RX3-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("58000000"),
                "rental_enabled": True,
                "rental_price": Decimal("1800000"),
                "stock_quantity": 6,
                "description": "Bàn DJ 2 kênh all-in-one sở hữu màn hình cảm ứng cực lớn 10.1 inch mượt mà, hỗ trợ Touch Preview và Release FX đa dạng.",
                "specifications": {
                    "Màn hình": "10.1 inch Touch Screen thế hệ mới",
                    "Số kênh": "2 kênh độc lập",
                    "Hiệu ứng": "14 Beat FX, 6 Sound Color FX, Release FX",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/xdj-rx3_large.png",
                "meta_title": "Bàn DJ Pioneer DJ XDJ-RX3 Màn Hình 10.1 Inch | VanBass",
                "meta_description": "Thiết bị DJ All-in-one Pioneer XDJ-RX3 tại VanBass Music Center.",
            },
            {
                "name": "Bàn điều khiển DJ Pioneer DJ DDJ-FLX4",
                "slug": "pioneer-dj-ddj-flx4",
                "sku": "DDJ-FLX4-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("12270000"),
                "rental_enabled": True,
                "rental_price": Decimal("400000"),
                "stock_quantity": 15,
                "description": "DJ controller 2 kênh phổ biến nhất thế giới cho người mới bắt đầu và DJ di động, tương thích rekordbox và Serato DJ Lite trên iPhone, Android, PC, Mac.",
                "specifications": {
                    "Số kênh": "2 kênh",
                    "Cổng kết nối": "USB-C kép",
                    "Tính năng độc quyền": "Smart CFX, Smart Fader",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/ddj-flx4_large.png",
                "meta_title": "Bàn DJ Pioneer DDJ-FLX4 Chính Hãng Giá Tốt | VanBass",
                "meta_description": "Bàn DJ mini Pioneer DDJ-FLX4 chính hãng tại VanBass Music Center Đà Nẵng.",
            },
            {
                "name": "Bàn điều khiển DJ 4 kênh Pioneer DJ DDJ-FLX10",
                "slug": "pioneer-dj-ddj-flx10",
                "sku": "DDJ-FLX10-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("45000000"),
                "rental_enabled": True,
                "rental_price": Decimal("1400000"),
                "stock_quantity": 5,
                "description": "Bàn điều khiển DJ 4 kênh chuyên nghiệp tích hợp công nghệ tách giọng hát/trống/nhạc cụ Track Separation thời gian thực và On Jog Display hiển thị dạng sóng nhiều chế độ.",
                "specifications": {
                    "Số kênh": "4 kênh + DMX output điều khiển ánh sáng",
                    "Công nghệ": "Track Separation (Vocal, Drums, Inst)",
                    "Mâm xoay": "On Jog Display tùy chỉnh 4 chế độ",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/ddj-flx10_large.png",
                "meta_title": "Bàn DJ 4 Kênh Pioneer DDJ-FLX10 Track Separation | VanBass",
                "meta_description": "Mua bàn DJ Pioneer DDJ-FLX10 chính hãng tại VanBass.",
            },
            {
                "name": "Mâm đĩa than kỹ thuật số & Analog Pioneer DJ PLX-CRSS12",
                "slug": "pioneer-dj-plx-crss12",
                "sku": "PLX-CRSS12-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("39500000"),
                "rental_enabled": True,
                "rental_price": Decimal("1200000"),
                "stock_quantity": 4,
                "description": "Mâm đĩa than Hybrid đột phá đầu tiên trên thế giới cho phép chơi DVS kỹ thuật số mà không cần tay cần (Tonearm/Needle) kết hợp khả năng chơi đĩa nhựa Vinyl analog thuần túy.",
                "specifications": {
                    "Chế độ": "Digital DVS không cần kim & Analog Vinyl",
                    "Động cơ": "Truyền động trực tiếp Direct Drive 3 pha",
                    "Hiệu năng": "4 Performance Pad tích hợp sẵn",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/plx-crss12_large.png",
                "meta_title": "Mâm Đĩa Than Pioneer DJ PLX-CRSS12 DVS Hybrid | VanBass",
                "meta_description": "Mâm đĩa than thế hệ mới Pioneer PLX-CRSS12 chính hãng.",
            },
            {
                "name": "Mâm đĩa than chuyên nghiệp Pioneer DJ PLX-1000",
                "slug": "pioneer-dj-plx-1000",
                "sku": "PLX-1000-PDJ",
                "category_slug": "dj",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("23500000"),
                "rental_enabled": True,
                "rental_price": Decimal("700000"),
                "stock_quantity": 6,
                "description": "Mâm đĩa than analog chuẩn Club với mô-men xoắn khởi động cực cao High-Torque, thiết kế khung kim loại đúc chống rung và cáp RCA mạ vàng tháo rời.",
                "specifications": {
                    "Mô-men xoắn khởi động": "4.5 kg/cm trở lên",
                    "Tốc độ quay": "33⅓ rpm, 45 rpm",
                    "Dải Pitch": "±8%, ±16%, ±50%",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/plx-1000_large.png",
                "meta_title": "Mâm Đĩa Than Chuyên Nghiệp Pioneer DJ PLX-1000 | VanBass",
                "meta_description": "Mâm đĩa than Analog Pioneer PLX-1000 tại VanBass Music Center.",
            },

            # === CATEGORY 2: MIXER & BÀN TRỘN (10 sản phẩm) ===
            {
                "name": "Bàn trộn âm thanh DJ AlphaTheta DJM-V5",
                "slug": "alphatheta-djm-v5",
                "sku": "DJM-V5-AT",
                "category_slug": "mixer",
                "brand": "AlphaTheta",
                "sale_enabled": True,
                "sale_price": Decimal("67200000"),
                "rental_enabled": True,
                "rental_price": Decimal("2000000"),
                "stock_quantity": 4,
                "description": "Mixer DJ 4 kênh chuyên nghiệp tích hợp bộ xử lý DSP 64-bit cao cấp, 14 Beat FX và bộ lọc Filter độc lập từng kênh âm thanh.",
                "specifications": {
                    "Số kênh": "4 kênh + 2 kênh Mic",
                    "Xử lý tín hiệu": "64-bit DSP",
                    "Soundcard": "Dual USB Type-C Soundcard",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/djm-v5_large.png",
                "meta_title": "Mixer DJ AlphaTheta DJM-V5 4 Kênh 64-bit | VanBass",
                "meta_description": "Mixer DJM-V5 chính hãng tại VanBass Music Center Đà Nẵng.",
            },
            {
                "name": "Bàn trộn âm thanh DJ Pioneer DJ DJM-A9",
                "slug": "pioneer-dj-djm-a9",
                "sku": "DJM-A9-PDJ",
                "category_slug": "mixer",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("72000000"),
                "rental_enabled": True,
                "rental_price": Decimal("2200000"),
                "stock_quantity": 4,
                "description": "Chuẩn mực Mixer 4 kênh cho các Club và Festival hàng đầu toàn cầu, tích hợp ESS Technology 32-bit DAC, Bluetooth và Soundcard kép.",
                "specifications": {
                    "Số kênh": "4 kênh âm thanh",
                    "Bộ giải mã DAC": "ESS Technology 32-bit DAC",
                    "Beat FX": "14 Beat FX kèm màn hình màu",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/djm-a9_large.png",
                "meta_title": "Mixer Pioneer DJ DJM-A9 Chuẩn Club Quốc Tế | VanBass",
                "meta_description": "Mua và thuê bàn trộn âm thanh Pioneer DJM-A9 tại Đà Nẵng.",
            },
            {
                "name": "Bàn trộn âm thanh Flagship Pioneer DJ DJM-V10",
                "slug": "pioneer-dj-djm-v10",
                "sku": "DJM-V10-PDJ",
                "category_slug": "mixer",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("95000000"),
                "rental_enabled": True,
                "rental_price": Decimal("2800000"),
                "stock_quantity": 2,
                "description": "Đỉnh cao Mixer DJ 6 kênh chuyên nghiệp, 4-band EQ, bộ nén âm Compressor từng kênh và bộ lọc Filter độc quyền cho các nghệ sĩ âm thanh khắt khe nhất.",
                "specifications": {
                    "Số kênh": "6 kênh âm thanh",
                    "EQ": "4-Band EQ từng kênh",
                    "Bộ xử lý": "96kHz/64-bit Mixing & Dithering",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/djm-v10_large.png",
                "meta_title": "Flagship Mixer 6 Kênh Pioneer DJ DJM-V10 | VanBass",
                "meta_description": "Pioneer DJM-V10 6 kênh cao cấp chính hãng tại VanBass.",
            },
            {
                "name": "Bàn trộn DJ Battle Scratch Pioneer DJ DJM-S11",
                "slug": "pioneer-dj-djm-s11",
                "sku": "DJM-S11-PDJ",
                "category_slug": "mixer",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("53000000"),
                "rental_enabled": True,
                "rental_price": Decimal("1600000"),
                "stock_quantity": 3,
                "description": "Mixer 2 kênh chuyên dụng cho DJ biểu diễn Scratch và Battle đỉnh cao với màn hình cảm ứng 4.3 inch tùy biến và Magvel Fader Pro siêu bền.",
                "specifications": {
                    "Màn hình": "4.3 inch Touch Screen",
                    "Crossfader": "Magvel Fader Pro mạ titan",
                    "Tính năng": "Smooth Echo, Touch FX, 22 Beat FX",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/djm-s11_large.png",
                "meta_title": "Mixer DJ Scratch Pioneer DJ DJM-S11 | VanBass",
                "meta_description": "Bàn trộn DJ Battle DJM-S11 chính hãng tại VanBass Đà Nẵng.",
            },
            {
                "name": "Bàn trộn DJ 2 kênh Pioneer DJ DJM-S7",
                "slug": "pioneer-dj-djm-s7",
                "sku": "DJM-S7-PDJ",
                "category_slug": "mixer",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("36000000"),
                "rental_enabled": True,
                "rental_price": Decimal("1100000"),
                "stock_quantity": 4,
                "description": "Mixer 2 kênh biểu diễn phong cách mở rộng, tích hợp kết nối Bluetooth và tích hợp sẵn chuẩn phần mềm Serato DJ Pro & rekordbox.",
                "specifications": {
                    "Số kênh": "2 kênh âm thanh + Bluetooth Input",
                    "Cần gạt FX": "Đòn bẩy gạt Effect lớn",
                    "Performance Pads": "16 Pad RGB đa chức năng",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/djm-s7_large.png",
                "meta_title": "Mixer DJ 2 Kênh Pioneer DJ DJM-S7 | VanBass",
                "meta_description": "Mixer Pioneer DJM-S7 chính hãng tại VanBass Music Center.",
            },
            {
                "name": "Bàn trộn âm thanh 2 kênh Pioneer DJ DJM-450",
                "slug": "pioneer-dj-djm-450",
                "sku": "DJM-450-PDJ",
                "category_slug": "mixer",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("18500000"),
                "rental_enabled": True,
                "rental_price": Decimal("600000"),
                "stock_quantity": 5,
                "description": "Mixer 2 kênh nhỏ gọn thừa hưởng bố cục và bộ xử lý 64-bit từ đàn anh DJM-900NXS2 cùng thanh trượt Magvel Fader mượt mà.",
                "specifications": {
                    "Xử lý tín hiệu": "64-bit Digital Signal Processor",
                    "Hiệu ứng": "Sound Color FX & Beat FX",
                    "Soundcard": "USB Soundcard tích hợp",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/djm-450_large.png",
                "meta_title": "Mixer DJ 2 Kênh Pioneer DJ DJM-450 | VanBass",
                "meta_description": "Mixer Pioneer DJM-450 chất lượng cao tại VanBass.",
            },
            {
                "name": "Bộ xử lý tín hiệu kỹ thuật số Marani Pro Audio DPA260P",
                "slug": "marani-pro-audio-dpa260p",
                "sku": "DPA260P-MRN",
                "category_slug": "mixer",
                "brand": "Marani Pro Audio",
                "sale_enabled": True,
                "sale_price": Decimal("14500000"),
                "rental_enabled": True,
                "rental_price": Decimal("500000"),
                "stock_quantity": 6,
                "description": "Bộ xử lý DSP kỹ thuật số 2 In 6 Out cho hệ thống âm thanh sân khấu chuyên nghiệp với độ trễ thấp và EQ thông minh.",
                "specifications": {
                    "Ngõ vào / ra": "2 Ngõ vào XLR, 6 Ngõ ra XLR",
                    "DSP": "24-bit AD/DA, 48kHz sampling rate",
                    "Bảo vệ": "Bộ giới hạn Limiter độc lập từng kênh",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/marani-dpa260p_large.png",
                "meta_title": "Bộ Xử Lý Âm Thanh DSP Marani DPA260P | VanBass",
                "meta_description": "Bộ xử lý DSP Marani DPA260P chính hãng tại VanBass Music Center.",
            },
            {
                "name": "Bộ xử lý tín hiệu cao cấp Marani Pro Audio DPA480P",
                "slug": "marani-pro-audio-dpa480p",
                "sku": "DPA480P-MRN",
                "category_slug": "mixer",
                "brand": "Marani Pro Audio",
                "sale_enabled": True,
                "sale_price": Decimal("22500000"),
                "rental_enabled": True,
                "rental_price": Decimal("700000"),
                "stock_quantity": 4,
                "description": "Hệ thống quản lý loa DSP 4 In 8 Out chất lượng âm thanh cao cấp, hỗ trợ bộ lọc FIR và kết nối điều khiển máy tính qua mạng RS485/USB.",
                "specifications": {
                    "Ngõ vào / ra": "4 In / 8 Out XLR mạ vàng",
                    "Bộ lọc": "Bộ lọc FIR, IIR, Crossover Butterworth/Bessel/Linkwitz-Riley",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/marani-dpa480p_large.png",
                "meta_title": "Bộ Quản Lý Loa DSP Marani DPA480P 4 In 8 Out | VanBass",
                "meta_description": "DSP Marani DPA480P cao cấp tại VanBass Đà Nẵng.",
            },
            {
                "name": "Cục đẩy công suất tích hợp DSP Marani MDA4-800DM",
                "slug": "marani-mda4-800dm",
                "sku": "MDA4-800DM-MRN",
                "category_slug": "mixer",
                "brand": "Marani Pro Audio",
                "sale_enabled": True,
                "sale_price": Decimal("38000000"),
                "rental_enabled": True,
                "rental_price": Decimal("1200000"),
                "stock_quantity": 3,
                "description": "Main công suất Class D 4 kênh hiệu suất cao 4x800W tích hợp sẵn bộ xử lý DSP đầy đủ tính năng tinh chỉnh loa.",
                "specifications": {
                    "Công suất": "4 x 800W @ 8 Ohm, 4 x 1400W @ 4 Ohm",
                    "Mạch công suất": "Class D PFC Switching Power Supply",
                    "DSP": "Tích hợp sẵn DSP điều khiển qua phần mềm",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/marani-mda4-800dm_large.png",
                "meta_title": "Cục Đẩy Công Suất 4 Kênh DSP Marani MDA4-800DM | VanBass",
                "meta_description": "Main công suất DSP Marani MDA4-800DM tại VanBass.",
            },
            {
                "name": "Bàn trộn âm thanh kỹ thuật số Behringer X32 Compact",
                "slug": "behringer-x32-compact",
                "sku": "X32-COMPACT-BHR",
                "category_slug": "mixer",
                "brand": "Behringer",
                "sale_enabled": True,
                "sale_price": Decimal("46000000"),
                "rental_enabled": True,
                "rental_price": Decimal("1500000"),
                "stock_quantity": 3,
                "description": "Bàn trộn kỹ thuật số 40 Input, 25 Bus với 16 tiền khuếch đại MIDAS có thể lập trình, 17 Fader động cơ và màn hình màu TFT 7 inch.",
                "specifications": {
                    "Kênh xử lý": "40 kênh đầu vào, 25 Bus",
                    "Preamp": "16 tiền khuếch đại Midas cao cấp",
                    "Fader": "17 Fader cơ giới 100mm",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/behringer-x32-compact_large.png",
                "meta_title": "Bàn Trộn Digital Behringer X32 Compact | VanBass",
                "meta_description": "Mixer kỹ thuật số Behringer X32 Compact tại VanBass Đà Nẵng.",
            },

            # === CATEGORY 3: LOA & PRO AUDIO (10 sản phẩm) ===
            {
                "name": "Loa di động biểu diễn AlphaTheta WAVE-EIGHT",
                "slug": "alphatheta-wave-eight",
                "sku": "WAVE-8-AT",
                "category_slug": "audio",
                "brand": "AlphaTheta",
                "sale_enabled": True,
                "sale_price": Decimal("26500000"),
                "rental_enabled": True,
                "rental_price": Decimal("800000"),
                "stock_quantity": 8,
                "description": "Loa DJ di động công nghệ không dây SonicLink siêu thấp độ trễ, pin sạc 8 giờ, chống nước IPX4 kèm tay kéo vali bánh xe tiện lợi.",
                "specifications": {
                    "Thời lượng pin": "Lên đến 8 giờ phát nhạc",
                    "Công nghệ": "SonicLink không dây độ trễ siêu thấp",
                    "Chống nước": "Chuẩn IPX4 ngoài trời",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/wave-eight_large.png",
                "meta_title": "Loa Di Động Không Dây SonicLink AlphaTheta WAVE-EIGHT | VanBass",
                "meta_description": "Loa DJ di động AlphaTheta WAVE-EIGHT chính hãng tại VanBass Music Center Đà Nẵng.",
            },
            {
                "name": "Hệ thống loa Cột PA JBL EON ONE MK2",
                "slug": "jbl-eon-one-mk2",
                "sku": "EON-ONE-MK2-JBL",
                "category_slug": "audio",
                "brand": "JBL",
                "sale_enabled": True,
                "sale_price": Decimal("32500000"),
                "rental_enabled": True,
                "rental_price": Decimal("1000000"),
                "stock_quantity": 5,
                "description": "Hệ thống loa Column PA tất cả trong một công suất đỉnh 1500W, pin rời 6 giờ, mixer 5 kênh số DSP Lexicon & dbx cao cấp.",
                "specifications": {
                    "Công suất": "1500W Peak / 400W RMS",
                    "SPL tối đa": "123 dB",
                    "DSP": "Lexicon Reverb, Chorus, Delay & dbx DriveRack",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/jbl-eon-one-mk2_large.png",
                "meta_title": "Loa Cột All-in-One JBL EON ONE MK2 1500W | VanBass",
                "meta_description": "Hệ thống loa JBL EON ONE MK2 chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Loa kiểm âm Monitor Pioneer DJ VM-50",
                "slug": "pioneer-dj-vm-50",
                "sku": "VM-50-PDJ",
                "category_slug": "audio",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("5400000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 12,
                "description": "Loa kiểm âm chủ động 5.25 inch công suất 60W Class D với bộ xử lý DSP 4 chế độ EQ tối ưu cho cả làm nhạc studio và chơi DJ tại nhà.",
                "specifications": {
                    "Củ loa": "Woofer 5.25 inch sợi Aramid, Tweeter 1 inch",
                    "Công suất": "60W Class D",
                    "DSP EQ": "4 cài đặt DSP DSP Low / High",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/vm-50_large.png",
                "meta_title": "Loa Kiểm Âm Studio Pioneer DJ VM-50 | VanBass",
                "meta_description": "Loa kiểm âm Pioneer VM-50 chính hãng tại VanBass.",
            },
            {
                "name": "Loa kiểm âm Monitor Pioneer DJ VM-70",
                "slug": "pioneer-dj-vm-70",
                "sku": "VM-70-PDJ",
                "category_slug": "audio",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("7200000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 8,
                "description": "Loa kiểm âm 6.5 inch công suất 100W mạnh mẽ với mặt trước bằng nhôm nguyên khối dày 4mm triệt tiêu rung chấn tối đa.",
                "specifications": {
                    "Củ loa": "Woofer 6.5 inch Aramid cone",
                    "Công suất": "100W (LF 70W + HF 30W)",
                    "Dải tần": "37 Hz - 36 kHz",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/vm-70_large.png",
                "meta_title": "Loa Kiểm Âm Pioneer DJ VM-70 100W | VanBass",
                "meta_description": "Loa kiểm âm Pioneer VM-70 chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Loa kiểm âm Monitor Pioneer DJ VM-80",
                "slug": "pioneer-dj-vm-80",
                "sku": "VM-80-PDJ",
                "category_slug": "audio",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("9100000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 6,
                "description": "Phiên bản loa kiểm âm cao cấp nhất dòng VM với củ loa Woofer 8 inch uy lực công suất 120W cho âm trầm sâu lắng và chính xác.",
                "specifications": {
                    "Củ loa": "Woofer 8 inch Aramid cone, Tweeter 1 inch",
                    "Công suất": "120W Class D",
                    "Dải tần": "34 Hz - 36 kHz",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/vm-80_large.png",
                "meta_title": "Loa Kiểm Âm Pioneer DJ VM-80 8 Inch 120W | VanBass",
                "meta_description": "Loa monitor studio Pioneer VM-80 tại VanBass Music Center.",
            },
            {
                "name": "Củ loa Subwoofer rời B&C Speakers 18TBX100 18 Inch",
                "slug": "bc-speakers-18tbx100",
                "sku": "18TBX100-BC",
                "category_slug": "audio",
                "brand": "B&C Speakers",
                "sale_enabled": True,
                "sale_price": Decimal("11800000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 10,
                "description": "Huyền thoại củ loa Sub rời 18 inch chuẩn sân khấu toàn cầu, cuộn dây coil 100mm (4 inch), công suất 2400W Program Made in Italy.",
                "specifications": {
                    "Đường kính": "18 inch (460 mm)",
                    "Công suất": "1200W RMS / 2400W Program",
                    "Độ nhạy": "97 dB (1W/1m)",
                    "Xuất xứ": "Made in Italy",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/bc-18tbx100_large.png",
                "meta_title": "Củ Loa Sub 18 Inch B&C Speakers 18TBX100 Italy | VanBass",
                "meta_description": "Củ loa rời B&C Speakers 18TBX100 chính hãng tại VanBass Music Center Đà Nẵng.",
            },
            {
                "name": "Củ loa Bass rời B&C Speakers 15TBX100 15 Inch",
                "slug": "bc-speakers-15tbx100",
                "sku": "15TBX100-BC",
                "category_slug": "audio",
                "brand": "B&C Speakers",
                "sale_enabled": True,
                "sale_price": Decimal("9600000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 8,
                "description": "Củ loa Bass rời 15 inch công suất 2000W Program chuyên dụng cho thùng loa Sub và Full chuyên nghiệp, cuộn coil 4 inch tản nhiệt nhôm kép.",
                "specifications": {
                    "Đường kính": "15 inch (380 mm)",
                    "Công suất": "1000W RMS / 2000W Program",
                    "Trở kháng": "8 Ohm",
                    "Xuất xứ": "Made in Italy",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/bc-15tbx100_large.png",
                "meta_title": "Củ Loa Bass 15 Inch B&C Speakers 15TBX100 Italy | VanBass",
                "meta_description": "Củ loa Bass 15 inch B&C 15TBX100 chính hãng tại VanBass.",
            },
            {
                "name": "Củ loa Bass Neodymium B&C Speakers 12NDL76 12 Inch",
                "slug": "bc-speakers-12ndl76",
                "sku": "12NDL76-BC",
                "category_slug": "audio",
                "brand": "B&C Speakers",
                "sale_enabled": True,
                "sale_price": Decimal("7800000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 8,
                "description": "Củ loa 12 inch sử dụng nam châm Neodymium siêu nhẹ và từ lực cực mạnh, công suất 1000W Program lý tưởng cho loa Line Array sân khấu.",
                "specifications": {
                    "Nam châm": "Neodymium trọng lượng siêu nhẹ",
                    "Công suất": "500W RMS / 1000W Program",
                    "Độ nhạy": "98.5 dB",
                    "Xuất xứ": "Made in Italy",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/bc-12ndl76_large.png",
                "meta_title": "Củ Loa Neodymium B&C Speakers 12NDL76 12 Inch | VanBass",
                "meta_description": "Củ loa B&C 12NDL76 nam châm Neo chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Củ Treble kèn Titanium B&C Speakers DE900TN Driver",
                "slug": "bc-speakers-de900tn",
                "sku": "DE900TN-BC",
                "category_slug": "audio",
                "brand": "B&C Speakers",
                "sale_enabled": True,
                "sale_price": Decimal("6200000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 12,
                "description": "Củ Treble kèn Driver nén cao cấp màng Titanium cuộn coil 3 inch nam châm Neodymium, dải tần đáp ứng lên đến 18kHz sắc nét.",
                "specifications": {
                    "Họng ra (Throat)": "1.4 inch (36 mm)",
                    "Màng loa": "Titanium cao cấp",
                    "Công suất": "140W Continuous / 280W Program",
                    "Xuất xứ": "Made in Italy",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/bc-de900tn_large.png",
                "meta_title": "Củ Treble Kèn B&C Speakers DE900TN Màng Titan | VanBass",
                "meta_description": "Củ Treble Driver B&C DE900TN chính hãng Italy tại VanBass.",
            },
            {
                "name": "Củ Treble kèn Polyimide B&C Speakers DE250 Driver",
                "slug": "bc-speakers-de250",
                "sku": "DE250-BC",
                "category_slug": "audio",
                "brand": "B&C Speakers",
                "sale_enabled": True,
                "sale_price": Decimal("3400000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 15,
                "description": "Củ Treble kèn 1 inch tiêu chuẩn ngành âm thanh với màng Polyimide cho tiếng Treble mềm mại tự nhiên và độ bền vô địch.",
                "specifications": {
                    "Họng ra (Throat)": "1 inch (25 mm)",
                    "Công suất": "60W RMS / 120W Program",
                    "Độ nhạy": "108.5 dB",
                    "Xuất xứ": "Made in Italy",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/bc-de250_large.png",
                "meta_title": "Củ Treble Kèn 1 Inch B&C Speakers DE250 Italy | VanBass",
                "meta_description": "Củ Treble B&C DE250 chính hãng tại VanBass Music Center.",
            },

            # === CATEGORY 4: HIỆU ỨNG & MÁY KHÓI ANTARI (10 sản phẩm) ===
            {
                "name": "Máy tạo khói sân khấu Antari Z-1000II 1000W",
                "slug": "antari-z-1000ii",
                "sku": "Z-1000II-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("8900000"),
                "rental_enabled": True,
                "rental_price": Decimal("350000"),
                "stock_quantity": 8,
                "description": "Máy tạo khói sân khấu 1000W công nghệ ECO giảm tiêu hao điện năng, lưu lượng khói mạnh mẽ kèm remote điều khiển từ xa.",
                "specifications": {
                    "Công suất": "1000W",
                    "Lưu lượng khói": "10,000 cu.ft/phút",
                    "Dung tích bình chứa": "1.7 lít",
                    "Thời gian khởi động": "5.5 phút",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-z1000ii_large.png",
                "meta_title": "Máy Tạo Khói Antari Z-1000II 1000W Chính Hãng | VanBass",
                "meta_description": "Bán & cho thuê máy tạo khói Antari Z-1000II tại Đà Nẵng.",
            },
            {
                "name": "Máy tạo khói sân khấu Antari Z-1500II 1500W",
                "slug": "antari-z-1500ii",
                "sku": "Z-1500II-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("16800000"),
                "rental_enabled": True,
                "rental_price": Decimal("600000"),
                "stock_quantity": 6,
                "description": "Máy phun khói sân khấu chuyên nghiệp 1500W công nghệ Unicore, màn hình LCD điều khiển DMX chuẩn sự kiện và bar club.",
                "specifications": {
                    "Công suất": "1500W",
                    "Lưu lượng khói": "20,000 cu.ft/phút",
                    "Dung tích bình": "6.0 lít",
                    "Điều khiển": "DMX 512 & LCD Panel",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-z1500ii_large.png",
                "meta_title": "Máy Phun Khói Sân Khấu Antari Z-1500II 1500W | VanBass",
                "meta_description": "Máy tạo khói Antari Z-1500II chính hãng tại VanBass Music Center Đà Nẵng.",
            },
            {
                "name": "Máy tạo khói công suất khủng Antari Z-3000II 3000W",
                "slug": "antari-z-3000ii",
                "sku": "Z-3000II-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("28500000"),
                "rental_enabled": True,
                "rental_price": Decimal("1000000"),
                "stock_quantity": 4,
                "description": "Cỗ máy tạo khói khổng lồ công suất 3000W chuyên phục vụ các đại nhạc hội ngoài trời, sân vận động và lễ hội âm nhạc quy mô lớn.",
                "specifications": {
                    "Công suất": "3000W",
                    "Lưu lượng khói": "40,000 cu.ft/phút",
                    "Dung tích bình": "6.0 lít",
                    "Điều khiển": "DMX 512 & Timer Remote",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-z3000ii_large.png",
                "meta_title": "Máy Tạo Khói Khủng 3000W Antari Z-3000II | VanBass",
                "meta_description": "Thuê máy tạo khói công suất lớn Antari Z-3000II tại Đà Nẵng.",
            },
            {
                "name": "Máy phun khói đứng LED RGBA Antari M-7 RGBA",
                "slug": "antari-m-7-rgba",
                "sku": "M-7-RGBA-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("22500000"),
                "rental_enabled": True,
                "rental_price": Decimal("800000"),
                "stock_quantity": 5,
                "description": "Máy phun cột khói đứng thẳng lên trời kết hợp 22 bóng LED RGBA công suất cao tạo hiệu ứng cột lửa CO2 khói rực rỡ nhiều màu sắc.",
                "specifications": {
                    "Hệ thống LED": "22 x 3W LED (Đỏ, Xanh lá, Xanh dương, Hổ phách)",
                    "Công suất phun": "1500W phun cột cao 5-8 mét",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-m7_large.png",
                "meta_title": "Máy Phun Khói Đứng LED RGBA Antari M-7 | VanBass",
                "meta_description": "Máy phun khói đứng LED Antari M-7 RGBA tại VanBass Music Center.",
            },
            {
                "name": "Máy tạo khói lạnh sàn tiệc cưới Antari Ice-101",
                "slug": "antari-ice-101",
                "sku": "ICE-101-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("24000000"),
                "rental_enabled": True,
                "rental_price": Decimal("900000"),
                "stock_quantity": 4,
                "description": "Máy tạo khói nặng / khói lạnh là đà mặt đất sử dụng đá lạnh thông thường (Ice Cube) tạo hiệu ứng bồng bềnh như mây cho sân khấu tiệc cưới và nhà hát.",
                "specifications": {
                    "Công suất": "1000W",
                    "Ngăn chứa đá": "10 kg đá lạnh viên",
                    "Diện tích phủ": "Khói chìm hoàn toàn dưới sàn không bốc cao",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-ice101_large.png",
                "meta_title": "Máy Tạo Khói Lạnh Sàn Antari Ice-101 | VanBass Đà Nẵng",
                "meta_description": "Thuê máy tạo khói lạnh tiệc cưới Antari Ice-101 tại Đà Nẵng.",
            },
            {
                "name": "Hệ thống tạo khói lạnh công nghiệp Antari DNG-250",
                "slug": "antari-dng-250",
                "sku": "DNG-250-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("68000000"),
                "rental_enabled": True,
                "rental_price": Decimal("2200000"),
                "stock_quantity": 2,
                "description": "Máy tạo khói lạnh công nghiệp tích hợp lốc máy nén làm lạnh gas không cần dùng đá lạnh hay đá khô CO2, hoạt động liên tục không giới hạn thời gian.",
                "specifications": {
                    "Hệ thống làm lạnh": "Lốc nén máy lạnh làm mát trực tiếp",
                    "Môi chất lạnh": "R-404A an toàn môi trường",
                    "Công suất": "Hoạt động liên tục 100% duty cycle",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-dng250_large.png",
                "meta_title": "Hệ Thống Khói Lạnh Antari DNG-250 Không Dùng Đá | VanBass",
                "meta_description": "Máy khói lạnh công nghiệp Antari DNG-250 tại VanBass.",
            },
            {
                "name": "Máy tạo sương mù mờ Fazer Antari F-1 Fazer",
                "slug": "antari-f-1-fazer",
                "sku": "F-1-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("19200000"),
                "rental_enabled": True,
                "rental_price": Decimal("700000"),
                "stock_quantity": 5,
                "description": "Máy tạo làn sương mờ mịn màng đều khắp không gian giúp nổi bật các tia đèn Laser và ánh sáng sân khấu mà không làm cay mắt khán giả.",
                "specifications": {
                    "Công suất": "800W",
                    "Quạt gió": "Tích hợp quạt thổi khuếch tán sương mù",
                    "Tiêu thụ": "Siêu tiết kiệm dung dịch khói",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-f1_large.png",
                "meta_title": "Máy Tạo Sương Mờ Sân Khấu Antari F-1 Fazer | VanBass",
                "meta_description": "Máy tạo khói mịn Fazer Antari F-1 chính hãng tại VanBass.",
            },
            {
                "name": "Quạt điều hướng gió sân khấu Antari AF-3",
                "slug": "antari-af-3",
                "sku": "AF-3-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("7800000"),
                "rental_enabled": True,
                "rental_price": Decimal("300000"),
                "stock_quantity": 8,
                "description": "Quạt gió sân khấu chuyên dụng 3 tốc độ điều khiển DMX hoặc cơ học giúp thổi khói, tạo gió hiệu ứng bay tóc nghệ sĩ biểu diễn.",
                "specifications": {
                    "Tốc độ gió": "3 mức tùy chỉnh (Low, Mid, High)",
                    "Điều khiển": "DMX 512 & Rotary Switch",
                    "Vỏ quạt": "Nhựa chống va đập nguyên khối",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-af3_large.png",
                "meta_title": "Quạt Gió Sân Khấu Chuyên Dụng Antari AF-3 | VanBass",
                "meta_description": "Quạt gió sân khấu Antari AF-3 chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Dung dịch tạo khói Heavy Fog Antari FLG-5 Can 5L",
                "slug": "antari-flg-5",
                "sku": "FLG-5-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("650000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 40,
                "description": "Dung dịch tạo khói đậm đặc gốc nước tiêu chuẩn Châu Âu, không mùi, không gây kích ứng, không để lại cặn dầu làm hỏng máy phun khói.",
                "specifications": {
                    "Dung tích": "Can 5 Lít",
                    "Đặc tính khói": "Khói trắng dày, lâu tan trong không khí",
                    "Chứng chỉ": "Đạt chuẩn an toàn CE, RoHS",
                    "Xuất xứ": "Made in Taiwan (Antari)",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-flg5_large.png",
                "meta_title": "Dung Dịch Tạo Khói Antari FLG-5 Can 5 Lít | VanBass",
                "meta_description": "Nước tạo khói Antari FLG-5 chính hãng giá tốt tại Đà Nẵng.",
            },
            {
                "name": "Dung dịch tạo khói nhanh tan Antari FLC-5 Can 5L",
                "slug": "antari-flc-5",
                "sku": "FLC-5-ATR",
                "category_slug": "stage-effects",
                "brand": "Antari",
                "sale_enabled": True,
                "sale_price": Decimal("680000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 30,
                "description": "Dung dịch tạo khói siêu nhanh tan chuyên dùng cho máy khói đứng LED hoặc hiệu ứng giả lập khí CO2 tan biến trong vài giây.",
                "specifications": {
                    "Dung tích": "Can 5 Lít",
                    "Đặc tính khói": "Khói bốc mạnh và tan biến nhanh trong 5-10 giây",
                    "Độ an toàn": "Gốc nước 100% không độc hại",
                    "Xuất xứ": "Made in Taiwan (Antari)",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/antari-flc5_large.png",
                "meta_title": "Dung Dịch Khói Nhanh Tan Antari FLC-5 Can 5L | VanBass",
                "meta_description": "Dung dịch tạo khói tan nhanh Antari FLC-5 chính hãng tại VanBass.",
            },

            # === CATEGORY 5: TAI NGHE & PHỤ KIỆN (10 sản phẩm) ===
            {
                "name": "Tai nghe DJ không dây SonicLink AlphaTheta HDJ-F10",
                "slug": "alphatheta-hdj-f10",
                "sku": "HDJ-F10-AT",
                "category_slug": "accessories",
                "brand": "AlphaTheta",
                "sale_enabled": True,
                "sale_price": Decimal("11500000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 10,
                "description": "Tai nghe DJ chuyên nghiệp đột phá với công nghệ truyền dẫn SonicLink siêu thấp độ trễ, pin 30 giờ và công nghệ chống ồn chủ động ANC cao cấp.",
                "specifications": {
                    "Kết nối": "SonicLink không dây siêu thấp trễ, Bluetooth 5.2, Dây cắm 3.5mm",
                    "Thời lượng pin": "9 giờ (SonicLink) / 30 giờ (Bluetooth)",
                    "Màng loa": "40 mm PEEK-PU-PEEK composite",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/hdj-f10_large.png",
                "meta_title": "Tai Nghe DJ Không Dây SonicLink AlphaTheta HDJ-F10 | VanBass",
                "meta_description": "Tai nghe DJ AlphaTheta HDJ-F10 chính hãng tại VanBass Music Center.",
            },
            {
                "name": "Tai nghe DJ chuyên nghiệp Pioneer DJ HDJ-X10",
                "slug": "pioneer-dj-hdj-x10",
                "sku": "HDJ-X10-PDJ",
                "category_slug": "accessories",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("9200000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 8,
                "description": "Flagship tai nghe DJ chuẩn phòng thu với dải tần siêu rộng 5Hz - 40,000Hz, đạt chuẩn độ bền chống sốc quân đội Mỹ MIL-STD-810G và đệm tai phủ Nano chống mồ hôi.",
                "specifications": {
                    "Dải tần đáp ứng": "5 Hz - 40,000 Hz",
                    "Màng loa": "50 mm HD driver",
                    "Độ bền": "Chuẩn quân đội MIL-STD-810G",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/hdj-x10_large.png",
                "meta_title": "Tai Nghe DJ Flagship Pioneer DJ HDJ-X10 | VanBass",
                "meta_description": "Tai nghe DJ Pioneer HDJ-X10 cao cấp chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Tai nghe DJ chuyên nghiệp Pioneer DJ HDJ-X7",
                "slug": "pioneer-dj-hdj-x7",
                "sku": "HDJ-X7-PDJ",
                "category_slug": "accessories",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("5800000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 10,
                "description": "Tai nghe DJ biểu diễn sở hữu củ loa 50mm mới phát triển, khả năng tách bạch âm bass và treble tuyệt hảo cho việc kiểm âm trong môi trường ồn ào.",
                "specifications": {
                    "Dải tần": "5 Hz - 30,000 Hz",
                    "Trở kháng": "36 Ohm",
                    "Độ nhạy": "102 dB",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/hdj-x7_large.png",
                "meta_title": "Tai Nghe DJ Pioneer DJ HDJ-X7 Chuyên Nghiệp | VanBass",
                "meta_description": "Tai nghe DJ Pioneer HDJ-X7 chính hãng tại VanBass.",
            },
            {
                "name": "Tai nghe DJ chuyên nghiệp Pioneer DJ HDJ-X5",
                "slug": "pioneer-dj-hdj-x5",
                "sku": "HDJ-X5-PDJ",
                "category_slug": "accessories",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("3200000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 15,
                "description": "Tai nghe DJ linh hoạt, âm bass chắc khỏe không bị méo tiếng ở mức âm lượng cao, thiết kế gập xoay đa hướng tiện lợi mang đi biểu diễn.",
                "specifications": {
                    "Màng loa": "40 mm Dome type",
                    "Dải tần": "5 Hz - 30,000 Hz",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/hdj-x5_large.png",
                "meta_title": "Tai Nghe DJ Pioneer DJ HDJ-X5 Chính Hãng | VanBass",
                "meta_description": "Tai nghe DJ Pioneer HDJ-X5 giá tốt tại VanBass Music Center.",
            },
            {
                "name": "Tai nghe DJ phong cách Pioneer DJ HDJ-CUE1",
                "slug": "pioneer-dj-hdj-cue1",
                "sku": "HDJ-CUE1-PDJ",
                "category_slug": "accessories",
                "brand": "Pioneer DJ",
                "sale_enabled": True,
                "sale_price": Decimal("1950000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 20,
                "description": "Tai nghe DJ nhỏ gọn, âm thanh chuẩn mực và thiết kế thời trang cho phép thay đổi màu sắc dây cáp và đệm tai theo cá tính.",
                "specifications": {
                    "Màng loa": "40 mm",
                    "Dải tần": "5 Hz - 30,000 Hz",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/hdj-cue1_large.png",
                "meta_title": "Tai Nghe DJ Pioneer DJ HDJ-CUE1 Giá Rẻ | VanBass",
                "meta_description": "Tai nghe DJ Pioneer HDJ-CUE1 chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Hệ thống micro không dây kỹ thuật số Sennheiser EW-D SKM-S Base Set",
                "slug": "sennheiser-ew-d-skm-s",
                "sku": "EW-D-SKM-SNH",
                "category_slug": "accessories",
                "brand": "Sennheiser",
                "sale_enabled": True,
                "sale_price": Decimal("18900000"),
                "rental_enabled": True,
                "rental_price": Decimal("600000"),
                "stock_quantity": 6,
                "description": "Hệ thống micro không dây UHF kỹ thuật số thế hệ mới với dải động 134 dB cao nhất thị trường, điều khiển qua ứng dụng Sennheiser Smart Assist Bluetooth.",
                "specifications": {
                    "Dải tần UHF": "56kHz equidistant tuning grid",
                    "Dải động": "134 dB (không cần chỉnh gain)",
                    "Thời lượng pin": "Lên đến 12 giờ với pin sạc BA 70",
                    "Bảo hành": "Chính hãng 24 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/sennheiser-ewd_large.png",
                "meta_title": "Micro Không Dây Digital Sennheiser EW-D SKM-S | VanBass",
                "meta_description": "Micro không dây cao cấp Sennheiser EW-D chính hãng tại VanBass Music Center Đà Nẵng.",
            },
            {
                "name": "Đầu Capsule micro vocal Sennheiser MMD 945",
                "slug": "sennheiser-mmd-945",
                "sku": "MMD-945-SNH",
                "category_slug": "accessories",
                "brand": "Sennheiser",
                "sale_enabled": True,
                "sale_price": Decimal("6200000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 10,
                "description": "Đầu củ micro dynamic Supercardioid cao cấp cho giọng hát dày dặn, âm sắc chi tiết và chống hú rít tuyệt đối trong các sự kiện sân khấu ồn ào.",
                "specifications": {
                    "Búp sóng (Pattern)": "Supercardioid chống hú",
                    "Loại đầu thu": "Dynamic",
                    "Tương thích": "Gắn vừa cho tay micro Sennheiser EW-D, EW-G4, 2000 series",
                    "Bảo hành": "Chính hãng 24 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/sennheiser-mmd945_large.png",
                "meta_title": "Đầu Micro Cao Cấp Sennheiser MMD 945 Supercardioid | VanBass",
                "meta_description": "Đầu củ micro Sennheiser MMD 945 chính hãng tại VanBass.",
            },
            {
                "name": "Micro có dây chuyên nghiệp Sennheiser E835-S",
                "slug": "sennheiser-e835-s",
                "sku": "E835-S-SNH",
                "category_slug": "accessories",
                "brand": "Sennheiser",
                "sale_enabled": True,
                "sale_price": Decimal("2850000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 15,
                "description": "Micro dynamic có dây chuyên dụng cho hát live và MC sự kiện, vỏ kim loại đúc chắc chắn tích hợp công tắc gạt On/Off êm ái.",
                "specifications": {
                    "Búp sóng": "Cardioid",
                    "Dải tần": "40 Hz - 16,000 Hz",
                    "Công tắc": "Có công tắc On/Off không gây tiếng 'bụp'",
                    "Bảo hành": "Chính hãng 24 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/sennheiser-e835s_large.png",
                "meta_title": "Micro Có Dây Sennheiser E835-S Chính Hãng | VanBass",
                "meta_description": "Micro hát live Sennheiser E835-S chính hãng tại Đà Nẵng.",
            },
            {
                "name": "Dây tín hiệu âm thanh cao cấp Klotz Titanium Guitar Cable 6m",
                "slug": "klotz-titanium-cable-6m",
                "sku": "TI-0600PP-KLZ",
                "category_slug": "accessories",
                "brand": "Klotz",
                "sale_enabled": True,
                "sale_price": Decimal("1850000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 20,
                "description": "Dây tín hiệu âm thanh Hi-End Made in Germany đầu jack mạ vàng 24K, điện dung cực thấp 75 pF/m cho chất âm thuần khiết không bị suy hao.",
                "specifications": {
                    "Chiều dài": "6.0 mét",
                    "Đầu nối": "Jack 6.3mm Neutrik mạ vàng 24K",
                    "Xuất xứ": "Made in Germany",
                    "Bảo hành": "Trọn đời sản phẩm (Lifetime Warranty)",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/klotz-titanium_large.png",
                "meta_title": "Dây Tín Hiệu Klotz Titanium 6m Made in Germany | VanBass",
                "meta_description": "Dây cáp tín hiệu âm thanh Klotz Titanium chính hãng tại VanBass.",
            },
            {
                "name": "Dây micro XLR chuyên dụng Klotz Greyhound 10m",
                "slug": "klotz-greyhound-cable-10m",
                "sku": "GRH1FP100-KLZ",
                "category_slug": "accessories",
                "brand": "Klotz",
                "sale_enabled": True,
                "sale_price": Decimal("850000"),
                "rental_enabled": False,
                "rental_price": None,
                "stock_quantity": 25,
                "description": "Cáp micro XLR đực - cái chất lượng cao chống nhiễu tuyệt đối, vỏ cao su dẻo dai chịu lực giẫm đạp trong các show diễn trực tiếp.",
                "specifications": {
                    "Chiều dài": "10 mét",
                    "Đầu nối": "XLR 3-pin Female sang XLR 3-pin Male",
                    "Xuất xứ": "Klotz Cables (Germany)",
                    "Bảo hành": "Chính hãng 12 tháng",
                },
                "image": "https://cdn.hstatic.net/products/200000465225/klotz-greyhound_large.png",
                "meta_title": "Dây Cáp Micro XLR Klotz Greyhound 10m | VanBass",
                "meta_description": "Dây micro XLR Klotz Greyhound 10m chính hãng tại Đà Nẵng.",
            },
        ]

        # Sync products into DB
        for p_data in products_data:
            existing_p = db.query(Product).filter(Product.slug == p_data["slug"]).first()
            category_id = cat_map[p_data["category_slug"]]

            if not existing_p:
                p = Product(
                    id=uuid.uuid4(),
                    category_id=category_id,
                    name=p_data["name"],
                    slug=p_data["slug"],
                    sku=p_data["sku"],
                    brand=p_data["brand"],
                    sale_enabled=p_data["sale_enabled"],
                    sale_price=p_data["sale_price"],
                    rental_enabled=p_data["rental_enabled"],
                    rental_price=p_data["rental_price"],
                    stock_quantity=p_data["stock_quantity"],
                    meta_title=p_data["meta_title"],
                    meta_description=p_data["meta_description"],
                    meta_keywords=f"{p_data['name'].lower()}, vanbass, vanbass music center",
                    canonical_url=f"https://vanbass.vn/products/{p_data['slug']}",
                    description=p_data["description"],
                    specifications=p_data["specifications"],
                    is_active=True,
                )
                db.add(p)
                db.flush()

                # Add Product Image
                p_img = ProductImage(
                    id=uuid.uuid4(),
                    product_id=p.id,
                    image_url=p_data["image"],
                    alt_text=p_data["name"],
                    sort_order=0,
                )
                db.add(p_img)
                print(f"Created product: [{p_data['category_slug'].upper()}] {p.name}")
            else:
                existing_p.category_id = category_id
                existing_p.name = p_data["name"]
                existing_p.sku = p_data["sku"]
                existing_p.brand = p_data["brand"]
                existing_p.sale_enabled = p_data["sale_enabled"]
                existing_p.sale_price = p_data["sale_price"]
                existing_p.rental_enabled = p_data["rental_enabled"]
                existing_p.rental_price = p_data["rental_price"]
                existing_p.stock_quantity = p_data["stock_quantity"]
                existing_p.meta_title = p_data["meta_title"]
                existing_p.meta_description = p_data["meta_description"]
                existing_p.description = p_data["description"]
                existing_p.specifications = p_data["specifications"]

                # Ensure image exists
                existing_img = db.query(ProductImage).filter(ProductImage.product_id == existing_p.id).first()
                if not existing_img:
                    p_img = ProductImage(
                        id=uuid.uuid4(),
                        product_id=existing_p.id,
                        image_url=p_data["image"],
                        alt_text=p_data["name"],
                        sort_order=0,
                    )
                    db.add(p_img)
                else:
                    existing_img.image_url = p_data["image"]
                    existing_img.alt_text = p_data["name"]

        db.commit()
        print("\n=======================================================")
        print(f"SUCCESS: Seeded 5 Categories and {len(products_data)} Authentic Products!")
        print("=======================================================\n")

    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
