"""simplify customer profile address

Revision ID: 88f54ccff0e6
Revises: 0842d9ed40b3
Create Date: 2026-08-13 11:16:43.200325

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88f54ccff0e6"
down_revision: str | Sequence[str] | None = "0842d9ed40b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_profiles", "district")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_profiles",
        sa.Column(
            "district", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
