"""add draft_data to home_configs

Revision ID: e728e94fe5ae
Revises: 4a09c0346330
Create Date: 2026-09-27 22:36:49.004104

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e728e94fe5ae'
down_revision: str | Sequence[str] | None = '4a09c0346330'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_configs', sa.Column('draft_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_configs', 'draft_data')
    # ### end Alembic commands ###
