import { Category, Product } from "./types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Thiết bị DJ",
    slug: "dj",
    number: "01",
    description: "DJ Controller, CDJ, All-In-One DJ Systems và thiết bị biểu diễn chuyên nghiệp.",
  },
  {
    id: "cat-2",
    name: "Mixer & Bàn trộn",
    slug: "mixer",
    number: "02",
    description: "DJ Mixers 2 kênh, 4 kênh, 6 kênh và bàn trộn âm thanh phòng thu / sự kiện.",
  },
  {
    id: "cat-3",
    name: "Loa & Pro Audio",
    slug: "audio",
    number: "03",
    description: "Loa kiểm âm Monitor, Loa di động biểu diễn, Subwoofer và hệ thống âm thanh sân khấu.",
  },
  {
    id: "cat-4",
    name: "Tai nghe & Phụ kiện",
    slug: "accessories",
    number: "04",
    description: "Tai nghe DJ không dây SonicLink, Bluetooth, cáp tín hiệu và phụ kiện DJ chuyên dụng.",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "gmusic-1",
    category_id: "cat-1",
    category_name: "Thiết bị DJ",
    category_slug: "dj",
    name: "Máy DJ AlphaTheta XDJ-AN",
    slug: "alphatheta-xdj-an",
    sku: "XDJ-AN",
    brand: "AlphaTheta",
    description:
      "Hệ thống DJ all-in-one thế hệ mới từ AlphaTheta. Thiết kế đột phá tích hợp màn hình cảm ứng sắc nét, hỗ trợ biểu diễn độc lập mà không cần máy tính.",
    specifications: {
      "Thương hiệu": "AlphaTheta (Pioneer DJ Corporation)",
      "Số kênh (Channels)": "2 kênh độc lập",
      "Màn hình cảm ứng": "7 inch Full-color Touch Screen",
      "Mâm xoay (Jog Wheel)": "Full-size On-Jog Display",
      "Định dạng âm thanh": "WAV, AIFF, FLAC, MP3, AAC",
      "Cổng kết nối": "USB-A x 2, USB-B x 1, Master Out (XLR/RCA)",
    },
    sale_enabled: true,
    sale_price: 37227600,
    rental_enabled: true,
    rental_price: 1200000,
    stock_quantity: 4,
    is_active: true,
  },
  {
    id: "gmusic-2",
    category_id: "cat-1",
    category_name: "Thiết bị DJ",
    category_slug: "dj",
    name: "Máy DJ AlphaTheta CDJ-1500X",
    slug: "alphatheta-cdj-1500x",
    sku: "CDJ-1500X",
    brand: "AlphaTheta",
    description:
      "Đầu phát DJ Player cao cấp thế hệ mới, hỗ trợ CloudDirectPlay, kết nối mạng Gigabit Pro DJ Link và khả năng xử lý tín hiệu âm thanh 32-bit siêu trung thực.",
    specifications: {
      "Thương hiệu": "AlphaTheta",
      "Màn hình": "9 inch HD Touch Display",
      "Tần số đáp ứng": "4 Hz - 40,000 Hz",
      "Bộ xử lý": "Advanced MPU đa lõi",
      "Pro DJ Link": "LAN Gigabit Ethernet",
      "Hỗ trợ kết nối": "USB-A, SD Card, Wi-Fi CloudDirectPlay",
    },
    sale_enabled: true,
    sale_price: 49680000,
    rental_enabled: true,
    rental_price: 1500000,
    stock_quantity: 3,
    is_active: true,
  },
  {
    id: "gmusic-3",
    category_id: "cat-1",
    category_name: "Thiết bị DJ",
    category_slug: "dj",
    name: "Đầu phát DJ AlphaTheta CDJ-3000X",
    slug: "alphatheta-cdj-3000x",
    sku: "CDJ-3000X",
    brand: "AlphaTheta",
    description:
      "Flagship DJ Player tối tân nhất thế giới cho các lễ hội âm nhạc và club quốc tế, sở hữu mâm xoay cơ học siêu mượt và độ trễ phản hồi thấp nhất lịch sử.",
    specifications: {
      "Thương hiệu": "AlphaTheta",
      "Bộ xử lý DAC": "Asahi Kasei DAC 32-bit",
      "Tốc độ Jog Wheel": "Cơ chế cải tiến giảm 50% độ trễ",
      "Touch Preview": "Nghe thử bài hát trực tiếp trên màn hình",
      "Kích thước": "329 x 453 x 118 mm / 5.5 kg",
    },
    sale_enabled: true,
    sale_price: 89910000,
    rental_enabled: true,
    rental_price: 2500000,
    stock_quantity: 2,
    is_active: true,
  },
  {
    id: "gmusic-4",
    category_id: "cat-2",
    category_name: "Mixer & Bàn trộn",
    category_slug: "mixer",
    name: "Mixer AlphaTheta DJM-V5",
    slug: "alphatheta-djm-v5",
    sku: "DJM-V5",
    brand: "AlphaTheta",
    description:
      "Bàn trộn DJ chuyên nghiệp với công nghệ DSP 64-bit, hệ thống lọc 4-band EQ tinh chỉnh chuyên sâu và tích hợp Send/Return đa hiệu ứng.",
    specifications: {
      "Thương hiệu": "AlphaTheta",
      "Số kênh": "4 kênh nhạc + 2 kênh Mic",
      "Bộ chuyển đổi D/A": "32-bit D/A Converter",
      "Effect": "Sound Color FX, Beat FX thế hệ mới",
      "USB Ports": "Dual USB-C cho 2 DJ chuyển set nhạc",
    },
    sale_enabled: true,
    sale_price: 67200000,
    rental_enabled: true,
    rental_price: 2000000,
    stock_quantity: 2,
    is_active: true,
  },
  {
    id: "gmusic-5",
    category_id: "cat-1",
    category_name: "Thiết bị DJ",
    category_slug: "dj",
    name: "Effector AlphaTheta RMX-Ignite",
    slug: "alphatheta-rmx-ignite",
    sku: "RMX-IGNITE",
    brand: "AlphaTheta",
    description:
      "Remix Station & Effector đỉnh cao dành cho các nghệ sĩ biểu diễn DJ trực tiếp, tích hợp cảm ứng chạm đa điểm và hàng trăm hiệu ứng Build-up/Break-down.",
    specifications: {
      "Thương hiệu": "AlphaTheta",
      "Băng tần xử lý": "3-Band FX (Hi, Mid, Low)",
      "Touch Pad": "Đa điểm điện dung",
      "Đầu vào / Đầu ra": "RCA, 6.35mm Jack, MIDI In/Out",
    },
    sale_enabled: true,
    sale_price: 39800000,
    rental_enabled: true,
    rental_price: 1000000,
    stock_quantity: 3,
    is_active: true,
  },
  {
    id: "gmusic-6",
    category_id: "cat-1",
    category_name: "Thiết bị DJ",
    category_slug: "dj",
    name: "DJ Controller Pioneer DJ DDJ-FLX4-W",
    slug: "pioneer-dj-ddj-flx4-w",
    sku: "DDJ-FLX4-W",
    brand: "Pioneer DJ",
    description:
      "Phiên bản màu trắng giới hạn (White Edition) của controller 2 kênh bán chạy nhất thế giới. Tích hợp tính năng Smart Fader và Smart CFX hỗ trợ chuyển bài mượt mà.",
    specifications: {
      "Thương hiệu": "Pioneer DJ",
      "Màu sắc": "Trắng cao cấp (White)",
      "Số kênh": "2 kênh",
      "Phần mềm hỗ trợ": "rekordbox, Serato DJ Lite",
      "Kết nối": "USB-C, Bluetooth",
      "Trọng lượng": "2.1 kg",
    },
    sale_enabled: true,
    sale_price: 12270000,
    rental_enabled: true,
    rental_price: 400000,
    stock_quantity: 6,
    is_active: true,
  },
  {
    id: "gmusic-7",
    category_id: "cat-4",
    category_name: "Tai nghe & Phụ kiện",
    category_slug: "accessories",
    name: "Tai nghe Bluetooth Pioneer DJ HDJ-CUE1BT-R",
    slug: "pioneer-dj-hdj-cue1bt-r",
    sku: "HDJ-CUE1BT-R",
    brand: "Pioneer DJ",
    description:
      "Tai nghe DJ không dây màu đỏ cá tính tích hợp Bluetooth 5.0, củ loa 40mm tinh chỉnh âm trầm uy lực và kết cấu khớp xoay 90 độ tiện lợi khi kiểm âm.",
    specifications: {
      "Thương hiệu": "Pioneer DJ",
      "Màu sắc": "Đỏ (Red Edition)",
      "Loại củ loa": "Dynamic 40mm",
      "Thời lượng Pin": "Lên đến 30 giờ chơi nhạc",
      "Dải tần": "5 Hz - 30,000 Hz",
      "Trọng lượng": "250 g",
    },
    sale_enabled: true,
    sale_price: 3780000,
    rental_enabled: true,
    rental_price: 120000,
    stock_quantity: 10,
    is_active: true,
  },
  {
    id: "gmusic-8",
    category_id: "cat-4",
    category_name: "Tai nghe & Phụ kiện",
    category_slug: "accessories",
    name: "Tai nghe không dây AlphaTheta HDJ-F10",
    slug: "alphatheta-hdj-f10",
    sku: "HDJ-F10",
    brand: "AlphaTheta",
    description:
      "Tai nghe DJ chuyên nghiệp trang bị công nghệ kết nối không dây SonicLink độ trễ siêu thấp, công nghệ chống ồn chủ động ANC và chất âm chi tiết chuẩn phòng thu.",
    specifications: {
      "Thương hiệu": "AlphaTheta",
      "Công nghệ": "SonicLink Ultra-Low Latency, Bluetooth 5.2",
      "Chống ồn": "Active Noise Cancelling (ANC)",
      "Củ loa": "40mm PEEK-PU composite film",
      "Độ nhạy": "105 dB",
    },
    sale_enabled: true,
    sale_price: 11772000,
    rental_enabled: true,
    rental_price: 300000,
    stock_quantity: 5,
    is_active: true,
  },
  {
    id: "gmusic-9",
    category_id: "cat-2",
    category_name: "Mixer & Bàn trộn",
    category_slug: "mixer",
    name: "Mixer 4 kênh Pioneer DJ DJM-A9",
    slug: "pioneer-dj-djm-a9",
    sku: "DJM-A9",
    brand: "Pioneer DJ",
    description:
      "Bàn trộn âm thanh 4 kênh chuẩn club toàn cầu. Tích hợp Sound Color FX có nút Center Lock độc quyền và bộ chuyển đổi ESS Technology 32-bit đỉnh cao.",
    specifications: {
      "Thương hiệu": "Pioneer DJ",
      "Số kênh": "4 Audio Channels, 2 Mic Channels",
      "Hiệu ứng": "14 Beat FX, 6 Sound Color FX",
      "Kết nối": "2 cổng USB-A/B, Bluetooth Audio Input",
    },
    sale_enabled: true,
    sale_price: 72000000,
    rental_enabled: true,
    rental_price: 2000000,
    stock_quantity: 2,
    is_active: true,
  },
  {
    id: "gmusic-10",
    category_id: "cat-3",
    category_name: "Loa & Pro Audio",
    category_slug: "audio",
    name: "Loa di động không dây AlphaTheta WAVE-EIGHT",
    slug: "alphatheta-wave-eight",
    sku: "WAVE-EIGHT",
    brand: "AlphaTheta",
    description:
      "Loa biểu diễn di động chuẩn DJ tích hợp pin 8 giờ, tiêu chuẩn chống nước IPX4 và công nghệ SonicLink truyền âm thanh không dây không độ trễ.",
    specifications: {
      "Thương hiệu": "AlphaTheta",
      "Thời lượng Pin": "Lên đến 8 giờ",
      "Kháng nước": "IPX4 ngoài trời",
      "Công nghệ": "SonicLink Wireless DJ",
      "SPL tối đa": "120 dB",
    },
    sale_enabled: true,
    sale_price: 26500000,
    rental_enabled: true,
    rental_price: 800000,
    stock_quantity: 4,
    is_active: true,
  },
  {
    id: "gmusic-11",
    category_id: "cat-3",
    category_name: "Loa & Pro Audio",
    category_slug: "audio",
    name: "Hệ thống loa cột JBL EON ONE MK2",
    slug: "jbl-eon-one-mk2",
    sku: "EON-ONE-MK2",
    brand: "JBL Professional",
    description:
      "Hệ thống loa Column All-In-One chạy pin với công suất đỉnh 1500W, góc phủ âm 140° x 30° và tích hợp mixer kỹ thuật số 5 kênh Lexicon & dbx DSP.",
    specifications: {
      "Thương hiệu": "JBL Professional",
      "Công suất": "1500W Peak / 400W RMS",
      "Thời lượng Pin": "6 giờ sử dụng liên tục",
      "Mixer tích hợp": "5 kênh Digital Mixer",
      "Góc phủ âm": "140° H x 30° V",
    },
    sale_enabled: true,
    sale_price: 32500000,
    rental_enabled: true,
    rental_price: 900000,
    stock_quantity: 5,
    is_active: true,
  },
  {
    id: "gmusic-12",
    category_id: "cat-3",
    category_name: "Loa & Pro Audio",
    category_slug: "audio",
    name: "Củ loa rời Subwoofer B&C 18TBX100 (Ý)",
    slug: "loa-sub-bc-18tbx100",
    sku: "18TBX100",
    brand: "B&C Speakers",
    description:
      "Củ loa Subwoofer 18 inch huyền thoại sản xuất tại Ý với cuộn dây côn 100mm, công suất cực đại 2400W cho âm trầm siêu uy lực tại các vũ trường và sân khấu lớn.",
    specifications: {
      "Thương hiệu": "B&C Speakers (Made in Italy)",
      "Đường kính": "18 inch (460 mm)",
      "Công suất": "2400W Continuous / 1200W Nominal",
      "Độ nhạy": "97 dB",
      "Dải tần": "35 - 1000 Hz",
    },
    sale_enabled: true,
    sale_price: 8900000,
    rental_enabled: true,
    rental_price: 400000,
    stock_quantity: 8,
    is_active: true,
  },
];
